---
title: "About"
description: |
  Hi! Welcome to my site. I am a master's student at UC Santa Barbara specializing in Energy & Climate and Pollution Prevention Remediation. When I am not at school, I enjoy cooking, yoga, hiking, skiing, and spending time with friends. 
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

My interests include:

- Land-use impacts
- Renewable energy procurement
- Regenerative agriculture
- Corporate sustainability
- Data science 

## Education

**Master in Environmental Science & Management** | Bren School | University of California, Santa Barbara (2023) 

**Master's Project:** [Developing a Framework to idenitfy the best areas for rooftop solar on Multifamily Housing](https://bren.ucsb.edu/projects/identifying-key-development-regions-rooftop-solar-multifamily-housing-complexes-united)

### Coursework
**General:** Earth System Science, Environmental Biogeochemistry, Ecological Principles, Environmental Law, Environmental Policy
<br>
**Data science:** Data Analysis and Statistics; Advanced Data Analysis; Computing in Environmental Science; Geographical Information Systems <br>
**Energy:**Energy Demand Analysis; Energy, Technology, & the Environment; Electricity Markets

**Bachelor of Science in Biology** | Minor in Environmental and Ecological Engineering | Purdue University (2021)
<br>
<br>

### Purdue Coursework
**Environmental Engineering:** Environmental Sustainability; Industrial Ecology and LCA <br>
**Conservation:** Environmental & Conservation Biology, Soil Science, Advanced Ecology, Disease Ecology  
<br>
**Computing:** Statistical Methods in Biology, Programming with MM Objects (Computer Science Python)


